title: SellerPro OAuth Handler
  description: OAuth redirect handler for eBay API integration

  # Remove or change this line:
  # private: true

  # Fix the SSL enforcement:
  enforce_https: true

  exclude:
    - README.md
    - config/
    - docs/
    - .gitignore
    - .env*
    - "*.js"
    - "*.json"

  include:
    - index.html
    - 404.html

  plugins: []
  markdown: kramdown
  highlighter: rouge

  safe: true
  incremental: false
